development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  password: <%= ENV.fetch("REDIS_PASSWORD") %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  password: <%= ENV.fetch("REDIS_PASSWORD") %>
